---
- hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - role_test
   # - bofa_test

  tasks:
  - name: call included role
    include_role: 
      name: new-role
      #version: devel
